# from calc import *
from main import *


class Inp:
    def set2(outpt):
        outpt.massinput()
        outpt.mass2()
        outpt.pvrass()
        outpt.roistr()
        outpt.roirass()
        outpt.npvrass()
        outpt.irrmassiv()
        outpt.irrrass()
        outpt.pirass()
        outpt.pdprass()
        outpt.output_1()

    if __name__ == '__main__':
        print("Введите сколько проектов вы хотите рассчиать 3 или 2:")
        a = float(input())
        if a == 3.0:
            print("Ввод переменных 1 проекта")
            print("Ввод коэфицента")
            kf = float(input())
            print("Ввод инвестиций")
            inv = float(input())
            print("Ввод количества потоков")
            pot = float(input())
            a = Calculator(kf, inv, pot)
            set2(a)
            print("Ввод переменных 2 проекта")
            print("Ввод коэфицента")
            kf = float(input())
            print("Ввод инвестиций")
            inv = float(input())
            print("Ввод количества потоков")
            pot = float(input())
            b = Calculator(kf, inv, pot)
            set2(b)
            print("Ввод переменных 3 проекта")
            print("Ввод коэфицента")
            kf = float(input())
            print("Ввод инвестиций")
            inv = float(input())
            print("Ввод количества потоков")
            pot = float(input())
            c1 = Calculator(kf, inv, pot)
            set2(c1)

        else:
            print("Ввод переменных 1 проекта")
            print("Ввод коэфицента")
            kf = float(input())
            print("Ввод инвестиций")
            inv = float(input())
            print("Ввод количества потоков")
            pot = float(input())
            a = Calculator(kf, inv, pot)
            set2(a)
            print("Ввод переменных 2 проекта")
            print("Ввод коэфицента")
            kf = float(input())
            print("Ввод инвестиций")
            inv = float(input())
            print("Ввод количества потоков")
            pot = float(input())
            b = Calculator(kf, inv, pot)
            set2(b)
            Result2(a, b)